baseURL = "https://shielajz.me/"
languageCode = "en-us"
paginate = 6
theme = "portio-hugo"
title = "Shiela's Portfolio"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
[[menu.main]]
name = "Use Cases"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

# Sitemap Menu for use cases
[[menu.sitemap]]
name = "Sentiment and Behavioral Analysis"
url = "#"
weight = 1
[[menu.sitemap]]
name = "Conversational System"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Predictive Modeling"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Product Recommendation"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © shielaj 2023"
footerLogo = "images/contact/widget-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Pateros Sto Rosario Metro Manila"
email = "shejz.projects@gmail.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(63) 936 7766 932"

[params.map]
APIkey = "vOFlx6tTGZlFBiW4VEq4"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/icreatesolutions.tech"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/shana-jimenez-a5b475195/"
weight = 2
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/io_oicreate/"
weight = 3
[[params.social]]
icon = "fa-github"
url = "https://github.com/shejz"
weight = 4

